name: Main CI
on:
  push:
    branches:
      - main
jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        with:
          mode: bump
          with-v: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: release/major
          minor-label: release/minor
          patch-label: release/patch
          release-notes-prefix: -- begin release notes --
          release-notes-suffix: -- end release notes --
