name: Release Info
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]
jobs:
  check-pr:
    name: Validate Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1
        name: Validate Pull Request Metadata
        id: validate_release
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: release/major
          minor-label: release/minor
          patch-label: release/patch
          with-v: true
          release-notes-prefix: -- begin release notes --
          release-notes-suffix: -- end release notes --

      - name: echo bumped version
        run: echo ${{ steps.validate_release.outputs.version }}
